# =============================================================================
# Lazygit Configuration
# A simple terminal UI for git commands
# https://github.com/jesseduffield/lazygit
# =============================================================================

gui:
  # stuff relating to the UI
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showCommandLog: true
  showBottomLine: true
  showIcons: true
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
  commitLength:
    show: true
  skipNoStagedFilesWarning: false
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: arrowAndNumber
  skipHookCommand: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  language: auto
  timeFormat: "02 Jan 06 15:04 MST"
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    # only applicable to unix users
    manualCommit: false
    args: ""
  pulling:
    mode: auto
  skipHookCommand: false
  autoFetch: true
  autoRefresh: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  overrideGpg: false
  disableForcePushing: false
  commitPrefix:
    - pattern: ""
      replace: ""
  parseEmoji: false
  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false
  truncateCopiedCommitHashesTo: 12
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium
update:
  method: prompt
  days: 14
refresher:
  refreshInterval: 10
  fetchInterval: 60
confirmOnQuit: false
os:
  editCommand: ""
  editCommandTemplate: ""
  openCommand: ""
customCommands: []
keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: <left>
    nextPage: <right>
    gotoTop: <home>
    gotoBottom: <end>
    prevBlock: <pgup>
    nextBlock: <pgdown>
    prevBlock-alt: K
    nextBlock-alt: J
    # nextBlock-alt2: <S-Tab>  # Note: Shift+Tab may not be supported on all terminals
    jumpToBlock:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: "/"
    optionMenu: x
    # optionMenu-alt1: none  # No alternate keybinding
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirm-alt1: "y"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    scrollUpMain-alt2: <c-u>
    scrollDownMain-alt2: <c-d>
    executeShellCommand: ":"
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: "]"
    prevTab: "["
    nextScreenMode: "+"
    prevScreenMode: "_"
    undo: "z"
    redo: "<c-z>"
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-r>
    submitEditorText: "<enter>"
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
  status:
    checkForUpdate: "u"
    recentRepos: "<enter>"
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    ignoreFile: "i"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
    toggleTreeView: "`"
    openMergeOptions: "M"
    openStatusFilter: "b"
    confirmDiscard: "X"
  branches:
    createPullRequest: "o"
    viewPullRequestOptions: "O"
    copyPullRequestURL: "<c-y>"
    checkoutBranchByName: "c"
    forceCheckoutBranch: "F"
    rebaseBranch: "r"
    renameBranch: "R"
    mergeIntoCurrentBranch: "M"
    viewGitFlowOptions: "i"
    fastForward: "f"
    createTag: "T"
    pushTag: "P"
    setUpstream: "u"
    fetchRemote: "f"
  commits:
    squashDown: "s"
    renameCommit: "r"
    renameCommitWithEditor: "R"
    viewResetOptions: "g"
    markCommitAsFixup: "f"
    createFixupCommit: "F"
    squashAboveCommits: "S"
    moveDownCommit: "<c-j>"
    moveUpCommit: "<c-k>"
    amendToCommit: "A"
    pickCommit: "p"
    revertCommit: "t"
    cherryPickCopy: "c"
    pasteCommits: "v"
    markCommitAsPicked: "<space>"
    viewCommitFiles: "<enter>"
    checkoutCommit: "<c-o>"
    resetCherryPick: "<c-R>"
    copyCommitMessageToClipboard: "<c-y>"
  stash:
    popStash: "g"
    renameStash: "r"
  commitFiles:
    checkoutCommitFile: "c"
    openOldCommitFile: "o"
  main:
    toggleDragSelect: "a"
    toggleDragSelect-alt: "A"
    toggleSelectHunk: "c"
    pickBothHunks: "b"
  submodules:
    init: "i"
    update: "u"
    bulkMenu: "b"
  commitMessage:
    commitMenu: "<c-o>"
# Worktrees configuration
worktrees:
  # The path to display worktrees in the status view
  path: .git/worktrees
